config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create]

  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :description, presence: true
  validates :price_in_cents, numericality: {only_integer: true}



  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
  has_many :reviews
  has_many :users, through: :reviews

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, :email, presence: true

  has_many :reviews
  has_many :products, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      render login_path
    end

  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.new
    end

  end


  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path
    else
      render :new
    end

  end



  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to  products_url
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)

  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  before_action :ensure_logged_in, only: [:create, :destroy]
  before_action :load_product
  def show
    @reivew = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(reviews_params)
    @review.user = current_user
      if @review.save
        redirect_to products_path, notice: "Review created!"
      else
        flash[:alert] = "Invalid input"
        render :new
      end

  end

  def destroy
    @review = Reivew.find(params[:id])
    @review.destroy
  end

  def reviews_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, notice => "Logged In!"

    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice: "Logged Out!"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, notice: "Signd up!"
    else
      render :new
    end

  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!-- <head> -->
  <!-- <title>Rainforest</title> -->
  <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> -->
  <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <!-- <%= csrf_meta_tags %> -->
<!-- </head> -->
<body>
  <% if flash[:notice] %>
        <p id="notice"><%= flash[:notice] %></p>
      <% end %>
  <% if flash[:alert] %>
        <p id="alert"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>

      <p class="userinfo">
        <% if current_user %>
          Signed in as <%= current_user.name %>, <%= current_user.email %>. <%= link_to "Log out",  logout_path%>
        <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
        <% end %>
      </p>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

  <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h2> Edit this Product </h2>

<%= link_to "Back", product_path(@product) %>

<p>
<br>
<br>

</p>
<%= render 'form' %>

<!-- <%= form_for @product do |p| %>
<p>
  <%= p.label :name %> <br>
  <%= p.text_field :name %>
</p>

<p>
  <%= p.label :description %> <br>
  <%= p.text_area :description %>
</p>

<p>
  <%= p.label :price_in_cents %> <br>
  <%= p.number_field :price_in_cents %>
</p>

<p>
  <%= p.submit "Edit Product" %>
</p> -->

app/views/products/index.html.erb
<h1>All the Products</h1>

<% @products.each do |p| %>
<p>
  <strong>Product Name : </strong> <br>
  <%= p.name %> <br>
  <strong>Product Description : </strong> <br>

  <%= p.description %> <br>
  <strong>Product Price(in cents) : </strong> <br>

  <%= p.formatted_price %> <br>

  <%= link_to "Details", product_path(p.id) %>
</p>
<% end %>

app/views/products/new.html.erb
<h2> Add New Product </h2>

<%= link_to "Back", products_url %>

<p>
<br>
<br>

</p>
<%= render 'form' %>

<!-- <%= form_for @product do |p| %>
  <p>
    <%= p.label :name %> <br>
    <%= p.text_field :name %>
  </p>

  <p>
    <%= p.label :description %> <br>
    <%= p.text_area :description %>
  </p>

  <p>
    <%= p.label :price_in_cents %> <br>
    <%= p.number_field :price_in_cents %>
  </p>

  <p>
    <%= p.submit "Add Product" %>
  </p>

<% end %> -->

app/views/products/show.html.erb
<h2> Product Details</h2>

  <p>
    <strong>Product Name : </strong> <br>
    <%= @product.name %>
  </p>
  <p>
    <strong>Product Description : </strong> <br>
    <%= @product.description %>
  </p>
  <p>
    <strong>Product Price : </strong> <br>
    <%= @product.formatted_price %>
  </p>
  <h3> Reviews </h3>
  <div class="product_reviews">
    <ol>
      <% @product.reviews.each do |m| %>
      <li>

            <%= m.comment  %> <br>
            <% if m.user != nil %>
            <em>by: <%= m.user.name %></em> <br>
              <%= m.user.email %> <br>
              Added on:<%= m.created_at %>
            <% end %>


      </li>

      <% end %>


    </ol>

  </div>
  <div class="add_review">
    <% if current_user %>
      <h4>  New Review </h4>


  <%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

        <%= f.label :comment %> <br>
        <%= f.text_field :comment %> <br>
        <%= f.submit "Add review" %>
      <% end %>
    <% else %>
      <p> Please <%= link_to "Log in", login_path %> to add a new review</p>

    <% end %>




  </div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |u| %>
<% if @user.errors.any? %>
<div class="error message">
  <h2>Input is invalid</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li> <%= message %> </li>
    <% end %>
  <% end %>
  </ul>
</div>

  <div class="field">
    <%= u.label :name %><br/>
    <%= u.text_field :name %>
  </div>
  <div class="field">
    <%= u.label :email %><br/>
    <%= u.text_field :email %>
  </div>
  <div class="field">
    <%= u.label :password %><br/>
    <%= u.password_field :password %>
  </div>
  <div class="field">
    <%= u.label :password_confirmation %><br/>
    <%= u.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= u.submit %></div>
  <% end %>